### ISSUE TITLE
No polarity for the speaker on the Codec Zero

### ISSUE THREAD

**Issue by petercwallis** [raspberrypi/Pi-Codec#3]
The speaker I have has a positive and a negative, but the card does not.  I assume the polarity doesn't matter then - will report back if the magic smoke comes out...

**Comment by pelwell** [comment]
Speakers work equally well either way round, you are just swapping a push for a pull, and vice versa; polarity only matters when you have multiple speakers playing sounds that are meant to be coherent, either multiple mono outputs or two sides of a stereo image, in which case the polarities should match otherwise they can interfere destructively and sound strange.
